### ISSUE TITLE
Multiple PropTypes warnings in react 15.3.0

### ISSUE THREAD

**Issue by maullerz** [jquense/react-formal#73]
Issue explained here - https://fb.me/react-warning-dont-call-proptypes

For example:
```
Warning: You are manually calling a React.PropTypes validation function
for the `mapValue` prop on `Binding`.
This is deprecated and will not work in the next major version.
You may be seeing this warning due to a third-party PropTypes library.
```

**Comment by maullerz** [comment]
bump
it is really annoying 👿 
console in dev-tools become very dirty

<img width="666" alt="2016-08-11 14 17 55" src="https://cloud.githubusercontent.com/assets/5295025/17587114/c9d95cd0-5fce-11e6-8351-1140066c1245.png">

**Comment by kompot** [comment]
@jquense If you already have migration path in mind, I'd be glad to implement it to allow 15.3.0 support. React guys suggest using 3rd party libraries. Have you had a chance to take a look at those libs?

**Comment by jquense** [comment]
I'm one of the authors of the suggested libs :P 

in this case the propType is really custom to react-formal. It's a 1 line code change if anyone wants to PR it

**Comment by maullerz** [comment]
hey @jquense no need to fix any code in react-formal
just need to updated `react-bootstrap/react-prop-types` dependency
https://github.com/react-bootstrap/react-prop-types/issues/25

**Comment by maullerz** [comment]
ah, no, this resolves just part of all warnings
warnings left:
```
// react-formal
`value` prop on `Form`
`schema` prop on `Form`

// react-input-message
`group` prop on `MessageTrigger`

// topeka
`mapValue` prop on `Binding`
```

**Comment by sirgallifrey** [comment]
I'm trying to fix this, but I got stuk with topeka. 4.0 fixes the warnings but it's also a breaking update.

**Comment by rosskevin** [comment]
>I'm one of the authors of the suggested libs :P
>
>in this case the propType is really custom to react-formal. It's a 1 line code change if anyone wants to PR it

@jquense I'm willing to to the PR.  All we need to do is change the offending lines to use https://github.com/aackerman/PropTypes?

**Comment by jquense** [comment]
This a been fixed in the latest version folks, few days ago, sorry for not closing this out.

**Comment by rosskevin** [comment]
I must be resolving an old version as a transitive dependency. Thanks

**Comment by rosskevin** [comment]
@jquense - one error appears to be still present in the latest `0.22.2`:

> warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `schema` prop on `Form`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

My guess is that this is the offending line:
https://github.com/jquense/react-formal/blob/master/src/Form.jsx#L278

**Comment by sirgallifrey** [comment]
I too got that warning @rosskevin and one more:

> vendor.js:1336 Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `Form`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by web2style** [comment]
Yes, I get the warning mentioned by @rosskevin and @sirgallifrey too.

**Comment by rosskevin** [comment]
@jquense please reopen

**Comment by sirgallifrey** [comment]
I've made a PR #85
