### ISSUE TITLE
Field type='select' seems broken

### ISSUE THREAD

**Issue by maullerz** [jquense/react-formal#89]
Color select in Documentation didnt work now. `<select>` is empty.

<img width="254" alt="2016-09-20 14 28 46" src="https://cloud.githubusercontent.com/assets/5295025/18668532/a69d17a4-7f3e-11e6-82c9-4fd7f362dca6.png">

```
    <label>Favorite Color</label>
    <Form.Field name='colorId' type='select'>
      <option value={null}>Select a color...</option>
      <option value={0}>Red</option>
      <option value={1}>Yellow</option>
      <option value={2}>Blue</option>
      <option value={3}>other</option>
    </Form.Field>
```

**Comment by TheCrow1213** [comment]
+1, this was working before we upgraded to the newest version.

**Comment by tonilaukka** [comment]
Have you found a fix for this issue or did you just pin down to previous version?

**Comment by jquense** [comment]
it's been fixed in recent versions

**Comment by tonilaukka** [comment]
OK. It's still broken in documentation site. Does it use a different version?

**Comment by maullerz** [comment]
@tonilaukka just need to update docs sources

**Comment by maullerz** [comment]
Issue resolved
